
import { Box } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function SalaLayout({ children }) {
 return (
   
      
      <Box sx={{
        display:'flex',
        justifyContent:'center',
        width:'100%',
        fontFamily:'JetBrains Mono'
      }}>
       
          
            
        
        {children}
        </Box>
    
  )
}
